[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.0.1"

# Description
title = "HCRL ORBIT Environments"
description="Extension containing suite of HCRL environments for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/KyleM73/orbit"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"omni.isaac.orbit" = {}
"omni.isaac.orbit_assets" = {}
"omni.isaac.core" = {}
"omni.isaac.gym" = {}
"omni.replicator.isaac" = {}

[[python.module]]
name = "hcrl_orbit"
