[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.0.1"

# Description
title = "HCRL IsaacLab Environments"
description = "Extension containing suite of HCRL environments for robot learning."
readme = "README.md"
repository = "https://github.com/KyleM73/isaac.lab.hcrl.git"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"omni.isaac.isaac.lab" = {}

[[python.module]]
name = "isaac.lab.hcrl"
